name: hackathon
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm install --include=optional && npm run build
    run_command: npm start
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
